resource_url:
  font_keywords: ["/entry.swf","/resource.cfg"]
  after_keywords: ["/core.swf",]

file_manager:
  resource_save_path: "./essence_resource"

net_work:
  max_connection: 50
  timeout: 60

system:
  debug: True